### ISSUE TITLE
error log shows "the message queue lock expired, so consume later".

### ISSUE THREAD

**Issue by simon1005** [apache/rocketmq-client-go#491]
When I use Clustering model and orderly comsumer, My log file keeps reporting errors,
 The error is 'the message queue lock expired, so consume later'

**Comment by simon1005** [comment]
请问是否在顺序消费的时候, 锁没有关闭成功, 导致只能锁超时? 目前一直在报这个提示, 不知道是否正常?

**Comment by 13450891497** [comment]
顺序消费一直提示锁错误。请问这怎么解决
INFO[0000] lock MessageQueue                             MessageQueue="MessageQueue [topic=ADX, brokerName=broker-a, queueId=1]" consumerGroup=GID_ADX01 lockOK=false
WARN[0000] do defaultConsumer, add a new mq failed, because lock failed  MessageQueue="MessageQueue [topic=ADX, brokerName=broker-a, queueId=1]" consumerGroup=GID_ADX01

**Comment by HZL3151904214** [comment]
这个issue为什么关闭了？应该还没解决吧，我在issue：https://github.com/apache/rocketmq-client-go/issues/1080有提供了可能的解决方案，但是不知道改的对不对
