### ISSUE TITLE
windows版本 广播模式无法消费消息bug

### ISSUE THREAD

**Issue by topret** [apache/rocketmq-client-go#498]
1. bug 描述: "persist offset to .rocketmq_client_go  offset.json: The process cannot access the file because it is being used by another process.
1. bug 产生原因: FileReadAll 后没有关闭文件,导致文件不能被删除和改名
1. 处理修改文件:internal\utils\files.go 
1.1  FileReadAll 在 os.Open(path) 之后 增加 defer file.Close()
1.2. WriteToFile
把 if err != nil {
			_, err = bakFile.Write(prevContent)
		}
修改为 if err == nil

**Comment by ShannonDing** [comment]
close due to time too long. welcome to open it again if the issue not fixed.

**Comment by jackalyuan** [comment]
time="2022-03-04T11:30:04+08:00" level=error msg="remove .rocketmq_client_go\\mmd-op-consumer-groups\\10.5.11.107@10144\\offset.json" underlayError="remove .rocketmq_client_go\\mmd-op-consumer-groups\\10.5.11.107@10144\\offset.json: The process cannot access the file because it is being used by another process." 

time="2022-03-04T11:30:04+08:00" level=error msg="persist offset to .rocketmq_client_go\\mmd-op-consumer-groups\\10.5.11.107@10144\\offset.json" underlayError="rename .rocketmq_client_go\\mmd-op-consumer-groups\\10.5.11.107@10144\\offset.json.tmp .rocketmq_client_go\\mmd-op-consumer-groups\\10.5.11.107@10144\\offset.json: Access is denied."
